{{- if .Values.amf.configuration.metrics.enabled }}
apiVersion: v1
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: amf-servicemonitor
  labels:
    nf-type: amf
    release: {{ .Values.global_config.monitoring.prometheus.release.name }}
spec:
  selector:
    matchLabels:
      nf-type: amf
  endpoints:
  - port: metrics
    interval: {{ .Values.amf.configuration.metrics.interval }}
{{- end }}
     
