apiVersion: v1
kind: ConfigMap
metadata:
  name: bsf-cmap
  labels:
    nf-type: bsf
data:
  bsf.yaml: |
    db_uri: "{{ .Values.global_config.db_uri }}"

    logger:
        file: /open5gs/bsf.log
        {{- if .Values.global_config.logs.enabled }}
        level: {{ .Values.global_config.logs.log_level}}
        {{- end }}
    {{- if .Values.global_config.no_tls.enabled }}
    sbi:
      server:
        no_tls: true
        #cacert: @sysconfdir@/open5gs/tls/ca.crt
        #key: @sysconfdir@/open5gs/tls/udm.key
        #cert: @sysconfdir@/open5gs/tls/udm.crt
      client:
        no_tls: true
        #cacert: @sysconfdir@/open5gs/tls/ca.crt
        #key: @sysconfdir@/open5gs/tls/udm.key
        #cert: @sysconfdir@/open5gs/tls/udm.crt
    {{- end }}
    bsf:
      sbi:
        - dev: {{ .Values.global_config.host.interface }}
          port: {{ .Values.bsf.container_port.sbi }}
          {{- if .Values.global_config.sbi.advertise }}
          advertise: bsf-svc
          {{- end }}
        

    nrf:
      sbi:
        - name: nrf-svc
          port: {{ .Values.nrf.container_port.sbi }}