apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
spec:
  ports:
  - port: {{ .Values.mongodb.service.port }}
    targetPort: {{ .Values.mongodb.service.target_port }}
  selector:
    app: open5gs-mongodb
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: open5gs-mongodb
spec:
  serviceName: "mongodb-svc"
  selector:
    matchLabels:
      app: open5gs-mongodb
  template:
    metadata:
      labels:
        app: open5gs-mongodb
    spec:
      containers:
      - image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
        name: open5gs-mongodb
        imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
        command:
          - mongod
        args:
          - "--bind_ip=0.0.0.0"
        ports:
        - containerPort: {{ .Values.mongodb.container_port }}
          name: mongodb
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-persistent-storage
        emptyDir: {}
      nodeSelector:
        {{- .Values.mongodb.node_selector | toYaml | nindent 8 }}


