apiVersion: v1
kind: Service
metadata:
  name: nrf-svc
  labels:
    nf-type: nrf
spec:
  selector:
    nf-type: nrf
  ports:
    - name: sbi
      protocol: TCP
      port: {{ .Values.nrf.service.sbi.port }}   
      targetPort: {{ .Values.nrf.service.sbi.target_port }} 
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nrf-depl
  labels:
    nf-type: nrf
spec:
  replicas: {{ .Values.nrf.replicas }}
  selector:
    matchLabels:
      nf-type: nrf
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nrf-cmap.yaml") . | sha256sum }}
      labels:
        nf-type: nrf
    spec:  
      containers:
        - name: nrf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", "/open5gs/install/bin/open5gs-nrfd -c /open5gs/config-map/nrf.yaml"]
          ports:
            - name: sbi  
              containerPort: {{ .Values.nrf.container_port.sbi }}
          volumeMounts:
            - name: nrf-cmap
              mountPath: /open5gs/config-map/nrf.yaml
              subPath: "nrf.yaml"
      {{- if .Values.global_config.imagePullSecret.enabled }}
      imagePullSecrets:
        - name: "{{ .Values.global_config.imagePullSecret.name }}"
      {{- end }}
      volumes:
        - name: nrf-cmap
          configMap:
            name: nrf-cmap
      nodeSelector:
        {{- .Values.nrf.node_selector | toYaml | nindent 8 }}