apiVersion: v1
kind: ConfigMap
metadata:
  name: nssf-cmap
  labels:
    nf-type: nssf
data:
  nssf.yaml: |
    logger:
        file: /open5gs/nssf.log
        {{- if .Values.global_config.logs.enabled }}
        level: {{ .Values.global_config.logs.log_level}}
        {{- end }}
    {{- if .Values.global_config.no_tls.enabled }}
    sbi:
      server:
        no_tls: true
        #cacert: @sysconfdir@/open5gs/tls/ca.crt
        #key: @sysconfdir@/open5gs/tls/udm.key
        #cert: @sysconfdir@/open5gs/tls/udm.crt
      client:
        no_tls: true
        #cacert: @sysconfdir@/open5gs/tls/ca.crt
        #key: @sysconfdir@/open5gs/tls/udm.key
        #cert: @sysconfdir@/open5gs/tls/udm.crt
    {{- end }}
    nssf:
      sbi:     
        - dev: {{ .Values.global_config.host.interface }}
          port: {{ .Values.nssf.container_port.sbi }}
          {{- if .Values.global_config.sbi.advertise }}
          advertise: nssf-svc
          {{- end }}
      nsi:
        {{- .Values.nssf.configuration.nsi_list | toYaml | nindent 8 }}      
    nrf:
      sbi:
        - name: nrf-svc
          port: {{ .Values.nrf.container_port.sbi }}
      