apiVersion: v1
kind: Service
metadata:
  name: nssf-svc
  labels:
    nf-type: nssf
spec:
  selector:
    nf-type: nssf
  ports:
    - name: sbi
      protocol: TCP
      port: {{ .Values.nssf.service.sbi.port }}
      targetPort: {{ .Values.nssf.service.sbi.target_port }} 
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nssf-depl  
  labels:
    nf-type: nssf
spec:
  replicas: {{ .Values.nssf.replicas }}
  selector:
    matchLabels:
      nf-type: nssf
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nssf-cmap.yaml") . | sha256sum }}
      labels:
        nf-type: nssf
    spec:   
      containers:
        - name: nssf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", "/open5gs/install/bin/open5gs-nssfd -c /open5gs/config-map/nssf.yaml"]
          ports:
            - name: sbi
              containerPort: {{ .Values.nssf.container_port.sbi }}
          volumeMounts:
          - name: nssf-cmap
            mountPath: /open5gs/config-map/nssf.yaml
            subPath: "nssf.yaml"          
      {{- if .Values.global_config.imagePullSecret.enabled }}
      imagePullSecrets:
        - name: "{{ .Values.global_config.imagePullSecret.name }}"
      {{- end }}
      volumes:
        - name: nssf-cmap
          configMap:
            name: nssf-cmap
      nodeSelector:
        {{- .Values.nssf.node_selector | toYaml | nindent 8 }}