{{- if .Values.global_config.imagePullSecret.image_secret_creator.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Values.global_config.imagePullSecret.name }}
stringData:
  .dockerconfigjson: >-
      {
        "auths": {
          "{{ .Values.global_config.imagePullSecret.registry }}": {
            "username": "{{ .Values.global_config.imagePullSecret.username }}",
            "password": "{{ .Values.global_config.imagePullSecret.password }}"
          }
        }
      }
{{- end }}
