apiVersion: v1
kind: Service
metadata:
  name: udm-svc
  labels:
    nf-type: udm
spec:
  selector:
    nf-type: udm
  ports:
    - name: sbi
      protocol: TCP
      port: {{ .Values.udm.service.sbi.port }}     
      targetPort: {{ .Values.udm.service.sbi.target_port }}    
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: udm-depl
  labels:
    nf-type: udm
spec:
  replicas: {{ .Values.udm.replicas }}
  selector:
    matchLabels:
      nf-type: udm
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/udm-cmap.yaml") . | sha256sum }}
      labels:
        nf-type: udm
    spec:   
      containers:
        - name: udm
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", "/open5gs/install/bin/open5gs-udmd -c /open5gs/config-map/udm.yaml"]
          ports: 
            - name: sbi
              containerPort: {{ .Values.udm.container_port.sbi }}
          volumeMounts:
          - name: udm-cmap
            mountPath: /open5gs/config-map/udm.yaml
            subPath: "udm.yaml"
      {{- if .Values.global_config.imagePullSecret.enabled }}
      imagePullSecrets:
        - name: "{{ .Values.global_config.imagePullSecret.name }}"
      {{- end }}
      volumes:
        - name: udm-cmap
          configMap:
            name: udm-cmap
      nodeSelector:
        {{- .Values.udm.node_selector | toYaml | nindent 8 }}