apiVersion: v1
kind: Service
metadata:
  name: udr-svc
  labels:
    nf-type: udr
spec:
  selector:
    nf-type: udr
  ports:
    - name: sbi
      protocol: TCP
      port: {{ .Values.udr.service.sbi.port }}  
      targetPort: {{ .Values.udr.service.sbi.target_port }}  
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: udr-depl
  labels:
    nf-type: udr
spec:
  replicas: {{ .Values.udr.replicas }}
  selector:
    matchLabels:
      nf-type: udr
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/udr-cmap.yaml") . | sha256sum }}
      labels:
        nf-type: udr
    spec:   
      containers:
        - name: udr
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", "/open5gs/install/bin/open5gs-udrd -c /open5gs/config-map/udr.yaml"]
          ports: 
            - name: sbi
              containerPort: {{ .Values.udr.container_port.sbi }}
          volumeMounts:
          - name: udr-cmap
            mountPath: /open5gs/config-map/udr.yaml
            subPath: "udr.yaml"          
      {{- if .Values.global_config.imagePullSecret.enabled }}
      imagePullSecrets:
        - name: "{{ .Values.global_config.imagePullSecret.name }}"
      {{- end }}
      volumes:
        - name: udr-cmap
          configMap:
            name: udr-cmap
      nodeSelector:
        {{- .Values.udr.node_selector | toYaml | nindent 8 }}